model:
  arch: minigpt_v2
  model_type: pretrain
  max_txt_len: 1024
  end_sym: "</s>"
  low_resource: True
  prompt_template: '[INST] {} [/INST]'
  llama_model: "./Llama-2-7b-chat-hf" #原始模型
  ckpt: "" #lora微调的checkpoint
  lora_r: 64
  lora_alpha: 16


datasets:
  stance_detection_conversation:
    vis_processor:
      train:
        name: "blip2_image_eval"
        image_size: 448
    text_processor:
      train:
        name: "blip_caption"

evaluation_datasets:
  stance_detection_conversation:
    image_path: ./mm-mtcsd/Bitcoin/image #图片路径
    ann_path: ./mm-mtcsd/Bitcoin/test.json #文件路径
    target: Tesla
    max_new_tokens: 50
    batch_size: 8

run:
  task: image_text_pretrain

